name: dpull  
description: 面包屑小道.
url: http://www.dpull.com
paginate: 10 # pagination based on number of posts
paginate_path: "/page/:num"
permalink: "/blog/:title"
include: ["_static"]
exclude: ["README.md"] # files to exclude
encoding: utf-8
markdown: kramdown
highlighter: pygments
markdown_ext: md
#excerpt_separator: <!--more--> 
excerpt_separator: ----------
