name: dpull  
description: 面包屑小道.
url: http://www.dpull.com
paginate: 10 # pagination based on number of posts
paginate_path: "/page/:num"
permalink: "/blog/:title"
include: ["_static"]
exclude: ["README.md"] # files to exclude
encoding: utf-8
markdown: kramdown
highlighter: pygments
markdown_ext: md
#excerpt_separator: <!--more--> 
excerpt_separator: ----------

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
