name: dpull  
description: 面包屑小道.
url: http://www.dpull.com
paginate: 10 # pagination based on number of posts
paginate_path: "/page/:num"
permalink: "/blog/:title"
include: ["_static"]
exclude: ["README.md"] # files to exclude
pygments: true
encoding: utf-8
markdown: kramdown
extensions: ["fenced_code_blocks"]
markdown_ext: md
#excerpt_separator: <!--more--> 
excerpt_separator: ----------
